version: '3.8'

services:
  quarkus-orders-psql:
    image: postgres:13.3-alpine
    container_name: "quarkus-orders-psql"
    hostname: postgresql-server
    labels:
      br.dev.multicode.author: "Andre Ferreira <andre.dev.linux@gmail.com>"
      br.dev.multicode.license: "MIT"
    expose:
      - '5432'
    environment:
      POSTGRES_USER: mcorders
      POSTGRES_PASSWORD: mcorders
      POSTGRES_DB: mcorders
    networks:
      net-saga-orchestration:
        ipv4_address: "10.200.0.200"
  
  quarkus-sec-psql:
    image: postgres:13.3-alpine
    container_name: "quarkus-sec-psql"
    hostname: postgresql-server
    labels:
      br.dev.multicode.author: "Andre Ferreira <andre.dev.linux@gmail.com>"
      br.dev.multicode.license: "MIT"
    expose:
      - '5432'
    environment:
      POSTGRES_USER: mcsec
      POSTGRES_PASSWORD: mcsec
      POSTGRES_DB: mcsec
    networks:
      net-saga-orchestration:
        ipv4_address: "10.200.0.201"
  
  quarkus-inventory-psql:
    image: postgres:13.3-alpine
    container_name: "quarkus-inventory-psql"
    hostname: postgresql-server
    labels:
      br.dev.multicode.author: "Andre Ferreira <andre.dev.linux@gmail.com>"
      br.dev.multicode.license: "MIT"
    expose:
      - '5432'
    environment:
      POSTGRES_USER: mcinventory
      POSTGRES_PASSWORD: mcinventory
      POSTGRES_DB: mcinventory
    networks:
      net-saga-orchestration:
        ipv4_address: "10.200.0.202"
  
  quarkus-payments-psql:
    image: postgres:13.3-alpine
    container_name: "quarkus-payments-psql"
    hostname: postgresql-server
    labels:
      br.dev.multicode.author: "Andre Ferreira <andre.dev.linux@gmail.com>"
      br.dev.multicode.license: "MIT"
    expose:
      - '5432'
    environment:
      POSTGRES_USER: mcpayments
      POSTGRES_PASSWORD: mcpayments
      POSTGRES_DB: mcpayments
    networks:
      net-saga-orchestration:
        ipv4_address: "10.200.0.203"
  
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      net-saga-orchestration:
        ipv4_address: "10.200.0.198"
  
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    container_name: kafka
    depends_on:
      - zookeeper
    expose:
      - 9092
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://10.200.0.199:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      net-saga-orchestration:
        ipv4_address: "10.200.0.199"
  
  jaeger:
    image: 'jaegertracing/all-in-one:latest'
    container_name: "jaeger"
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '14268:14268'
      - '14250:14250'
      - '16686:16686'
    expose:
      - '5775'
      - '6831'
      - '6832'
      - '5778'
      - '14268'
      - '14250'
      - '16686'
    networks:
      net-saga-orchestration:
        ipv4_address: "10.200.0.197"

networks:
  net-saga-orchestration:
    name: net-saga-orchestration
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.200.0.0/24